import Foundation
import XCTest
@testable import AgenticSidebar

@MainActor
final class ClipboardMonitorServiceTests: XCTestCase {
    func testConcealedClipboardContentIsNeverSubmitted() async {
        let pasteboard = FakePasteboard()
        let recorder = SubmissionRecorder()
        let service = await makeService(recorder: recorder)
        let monitor = makeMonitor(
            service: service,
            pasteboard: pasteboard,
            autoSubmitClipboard: true
        )

        pasteboard.setString(
            "hunter2",
            additionalTypes: ["org.nspasteboard.ConcealedType"]
        )
        monitor.tick()

        let submissions = await recorder.submissions()
        XCTAssertTrue(submissions.isEmpty)
    }

    func testEnablingTheFeatureDoesNotSubmitStaleClipboardContent() async throws {
        let pasteboard = FakePasteboard()
        let recorder = SubmissionRecorder()
        let service = await makeService(recorder: recorder)
        let monitor = makeMonitor(
            service: service,
            pasteboard: pasteboard,
            autoSubmitClipboard: false
        )

        // Copied while automation was disabled; enabling it later must not send it.
        pasteboard.setString("stale-secret")
        monitor.tick()

        try XCTUnwrap(settingsStore).autoSubmitClipboard = true
        monitor.tick()

        let submissions = await recorder.submissions()
        XCTAssertTrue(
            submissions.isEmpty,
            "Enabling auto-send must never submit content copied before the opt-in"
        )
    }

    func testFreshCopyIsSubmittedOnce() async {
        let pasteboard = FakePasteboard()
        let recorder = SubmissionRecorder()
        let service = await makeService(recorder: recorder)
        let monitor = makeMonitor(
            service: service,
            pasteboard: pasteboard,
            autoSubmitClipboard: true
        )

        pasteboard.setString("explain this error")
        monitor.tick()

        let submissions = await waitForSubmissions(recorder, count: 1)
        XCTAssertEqual(submissions, ["explain this error"])

        XCTAssertEqual(pasteboard.stringReadCount(), 1)

        monitor.tick()
        let repeated = await waitForSubmissions(recorder, count: 1)
        XCTAssertEqual(repeated, ["explain this error"])
        XCTAssertEqual(
            pasteboard.stringReadCount(),
            1,
            "Polling without a clipboard change must not read the payload"
        )
    }

    func testCopyDuringAnActiveTurnIsQueuedUntilTheSessionIsIdle() async throws {
        let pasteboard = FakePasteboard()
        let recorder = SubmissionRecorder()
        let pair = AsyncThrowingStream<ProviderEvent, Error>.makeStream()
        let service = await makeService(recorder: recorder, streamFactory: { _ in
            ProviderStream(events: pair.stream)
        })
        let monitor = makeMonitor(
            service: service,
            pasteboard: pasteboard,
            autoSubmitClipboard: true
        )

        let activeTask = try XCTUnwrap(service.submit("first turn"))
        XCTAssertFalse(service.canSubmit)

        pasteboard.setString("second turn")
        monitor.tick()

        var submissions = await waitForSubmissions(recorder, count: 1)
        XCTAssertEqual(submissions, ["first turn"])

        pair.continuation.yield(.completed)
        pair.continuation.finish()
        await activeTask.value

        monitor.tick()

        submissions = await waitForSubmissions(recorder, count: 2)
        XCTAssertEqual(
            submissions,
            ["first turn", "second turn"],
            "A copy that arrived while the session was busy must not be dropped"
        )
    }

    func testPrivacyMarkerCheckCoversTheStandardTypes() {
        for type in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ] {
            let snapshot = PasteboardSnapshot(
                changeCount: 1,
                types: ["public.utf8-plain-text", type],
                containsImage: false
            )

            XCTAssertTrue(PasteboardPrivacyMarker.isMarked(snapshot))
        }

        let plain = PasteboardSnapshot(
            changeCount: 1,
            types: ["public.utf8-plain-text"],
            containsImage: false
        )
        XCTAssertFalse(PasteboardPrivacyMarker.isMarked(plain))
    }

    private var settingsStore: SettingsStore?
    private var settingsSuiteName: String?

    /// Submissions are performed by a detached MainActor task, so the recorder is
    /// polled instead of asserted synchronously.
    private func waitForSubmissions(
        _ recorder: SubmissionRecorder,
        count: Int
    ) async -> [String] {
        for _ in 0..<200 {
            let submissions = await recorder.submissions()
            if submissions.count >= count {
                return submissions
            }
            try? await Task.sleep(for: .milliseconds(5))
        }

        return await recorder.submissions()
    }

    override func tearDown() async throws {
        if let settingsSuiteName {
            UserDefaults(suiteName: settingsSuiteName)?
                .removePersistentDomain(forName: settingsSuiteName)
        }
        settingsStore = nil
        settingsSuiteName = nil
        try await super.tearDown()
    }

    private func makeMonitor(
        service: AgentSessionService,
        pasteboard: FakePasteboard,
        autoSubmitClipboard: Bool
    ) -> ClipboardMonitorService {
        let suiteName = "AgenticSidebarTests.Clipboard.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName)!
        defaults.removePersistentDomain(forName: suiteName)

        let store = SettingsStore(defaults: defaults)
        store.autoSubmitClipboard = autoSubmitClipboard
        settingsStore = store
        settingsSuiteName = suiteName

        return ClipboardMonitorService(
            sessionService: service,
            settingsStore: store,
            pasteboard: pasteboard
        )
    }

    private func makeService(
        recorder: SubmissionRecorder,
        streamFactory: @escaping @Sendable (ProviderRequest) async throws -> ProviderStream = { _ in
            completedStream()
        }
    ) async -> AgentSessionService {
        let runtime = TestProviderRuntime(
            id: ProviderID("alpha"),
            displayName: "Alpha",
            models: [
                ProviderModelCapability(
                    id: ProviderModelID("alpha-1"),
                    displayName: "Alpha 1",
                    variants: []
                )
            ],
            streamFactory: { request in
                await recorder.record(request)
                return try await streamFactory(request)
            }
        )

        let service = AgentSessionService(runtimes: [runtime])
        await service.refreshCapabilities()
        return service
    }
}

private func completedStream() -> ProviderStream {
    let pair = AsyncThrowingStream<ProviderEvent, Error>.makeStream()
    pair.continuation.yield(.assistantTextDelta("ok"))
    pair.continuation.yield(.completed)
    pair.continuation.finish()
    return ProviderStream(events: pair.stream)
}

private final class FakePasteboard: PasteboardReading, @unchecked Sendable {
    private let lock = NSLock()
    private var snapshotValue = PasteboardSnapshot(
        changeCount: 0,
        types: [],
        containsImage: false
    )
    private var text: String?
    private var reads = 0

    func snapshot() -> PasteboardSnapshot {
        lock.withLock { snapshotValue }
    }

    func currentString() -> String? {
        lock.withLock {
            reads += 1
            return text
        }
    }

    func imagePNGData() -> Data? {
        nil
    }

    func stringReadCount() -> Int {
        lock.withLock { reads }
    }

    func setString(_ value: String, additionalTypes: [String] = []) {
        lock.withLock {
            text = value
            snapshotValue = PasteboardSnapshot(
                changeCount: snapshotValue.changeCount + 1,
                types: ["public.utf8-plain-text"] + additionalTypes,
                containsImage: false
            )
        }
    }
}

private actor SubmissionRecorder {
    private var recorded: [String] = []

    func record(_ request: ProviderRequest) {
        recorded.append(request.messages.last?.text ?? "")
    }

    func submissions() -> [String] {
        recorded
    }
}
