import AppKit

/// A cheap read of the general pasteboard: change count, declared types and image
/// availability only. Text and image payloads are fetched separately so polling
/// never pays for content that is not needed.
struct PasteboardSnapshot: Equatable, Sendable {
    let changeCount: Int
    let types: [String]
    let containsImage: Bool
}

protocol PasteboardReading: Sendable {
    func snapshot() -> PasteboardSnapshot

    /// The current plain-text clipboard content. Called only after a change has
    /// been observed, because large payloads are expensive to read.
    func currentString() -> String?

    /// PNG representation of the current image content, or nil when the
    /// pasteboard holds no image. Only called when `snapshot().containsImage` is
    /// true, so the conversion cost is never paid for text-only copies.
    func imagePNGData() -> Data?
}

struct SystemPasteboardReader: PasteboardReading {
    func snapshot() -> PasteboardSnapshot {
        let pasteboard = NSPasteboard.general
        let types = pasteboard.types ?? []

        return PasteboardSnapshot(
            changeCount: pasteboard.changeCount,
            types: types.map(\.rawValue),
            containsImage: types.contains(.png) || types.contains(.tiff)
        )
    }

    func currentString() -> String? {
        NSPasteboard.general.string(forType: .string)
    }

    func imagePNGData() -> Data? {
        guard let image = NSImage(pasteboard: NSPasteboard.general) else {
            return nil
        }

        return ScreenshotImageEncoding.pngData(from: image)
    }
}

/// Pasteboard markers that applications set when content must not be recorded,
/// replayed, or forwarded. Password managers and clipboard utilities use these
/// types precisely so automation cannot leak secrets.
enum PasteboardPrivacyMarker {
    static let types: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type"
    ]

    static func isMarked(_ snapshot: PasteboardSnapshot) -> Bool {
        !types.isDisjoint(with: snapshot.types)
    }
}

enum ScreenshotImageEncoding {
    static func pngData(from image: NSImage) -> Data? {
        guard
            let tiff = image.tiffRepresentation,
            let bitmap = NSBitmapImageRep(data: tiff)
        else {
            return nil
        }

        return bitmap.representation(using: .png, properties: [:])
    }
}
